ludus:
  - vm_name: "{{ range_id }}-DC01"
    hostname: "DC01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 10
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: sentinel.lab
      role: primary-dc
    roles:
      - albert.ludus_ms_sentinel.setup_windows
      - albert.ludus_ms_sentinel.disable_defender
      # Log Analytics Agent would be installed here in a real Azure environment
      # We're simulating it in Ludus

  - vm_name: "{{ range_id }}-Workstation"
    hostname: "Workstation"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 4
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: sentinel.lab
      role: member
    roles:
      - albert.ludus_ms_sentinel.setup_windows
      - albert.ludus_ms_sentinel.disable_defender
      # Log Analytics Agent would be installed here in a real Azure environment
      # We're simulating it in Ludus

  - vm_name: "{{ range_id }}-Kali"
    hostname: "Kali"
    template: kali-template  # Ludus kali template
    vlan: 10
    ip_last_octet: 12
    ram_gb: 4
    cpus: 2
    roles:
      - albert.ludus_ms_sentinel.setup_kali

  # This section runs attacks after deployment
  - ludus:
      when: post-deploy
      host: Kali
    roles:
      - albert.ludus_ms_sentinel.attack_sequence
    role_vars:
      attack_types:
        - network_discovery
        - credential_access
        - persistence
        - defense_evasion
      target_ip: "10.10.10.11"  # IP of the Workstation (adjust based on your network)

  # Additional attack scenarios that can be run manually
  # Uncomment and modify as needed
  #- ludus:
  #    when: post-deploy
  #    host: Kali
  #  roles:
  #    - albert.ludus_ms_sentinel.install_atomic
  #  role_vars:
  #    technique_id: "T1003.001"  # Credential Dumping
